### ISSUE TITLE
`dontcare` values

### ISSUE THREAD

**Issue by Guppy16** [smartyfh/MultiWOZ2.4#10]
Hi,

When the slot value is `dontcare`, should we expect a model to predict `dontcare`, or should we assume that any model prediction is ok? E.g. is it ok for a model to predict `hotel=guest house` when the ground truth is `hotel=dontcare`?

**Comment by smartyfh** [comment]
> Hi,
> 
> When the slot value is `dontcare`, should we expect a model to predict `dontcare`, or should we assume that any model prediction is ok? E.g. is it ok for a model to predict `hotel=guest house` when the ground truth is `hotel=dontcare`?

No, the prediction should be dontcare.
