### ISSUE TITLE
Which TripPy result is valid?

### ISSUE THREAD

**Issue by ZhangzihanGit** [smartyfh/MultiWOZ2.4#6]
Hi, 

Thanks for your hard work. 

In the paper, the Joint goal accuracy for TriPy on MWZ2.4 is 59.62%, however, in the README table, the accuracy is 64.75%. Which one is valid? Thank you!

**Comment by smartyfh** [comment]
> Hi,
> 
> Thanks for your hard work.
> 
> In the paper, the Joint goal accuracy for TriPy on MWZ2.4 is 59.62%, however, in the README table, the accuracy is 64.75%. Which one is valid? Thank you!

Hi, 64.75% is the correct one. The arxiv paper has not been updated yet.

**Comment by ZhangzihanGit** [comment]
Thanks for the quick reply!
